spring:
  application:
    name: BookingManagementSystem
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 60000
book:
  maximumBorrowedByUser: 5
  borrowDuration: 30
  penaltyCents: 1000
embedded:
  redis: true
logging:
  level:
    org:
      springframework: INFO
    io:
      app: TRACE
  file:
    name: application.log